language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules
    - coverage
    - .nyc_output
    - dist

script: echo "Running tests against $(node -v) ..."

branches:
  only:
    - master
    - dev

jobs:
  include:
    - stage: test
      name: "Integration tests"
      script: npm run test:integration
    - script: npm run lint
      name: "Lint"
    - stage: coverage
      name: "Run code coverage"
      script:
        - npm install codecov -g
        - nyc report --reporter=json > coverage/coverage.json
        - codecov
    - stage: build
      name: "Build lib"
      script: npm run build
    - stage: npm release
      node_js: "10"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "mail@sebastianwessel.de"
        api_key: $NPM_API_KEY
        gem: eventstore-ts-client
        on:
          branch: master

stages:
  - test
  - coverage
  - name: build
    if: branch = master
  - name: npm release
    if: branch = master