dist: trusty

language: node_js

node_js:
  - "11"

install:
- nmp ci

cache:
  directories:
    - "$HOME/.npm"
    - node_modules
    - coverage
    - .nyc_output
    - .nyc_integration
    - .nyc_unit
    - dist

script: echo "Running tests against $(node -v) ..."

branches:
  only:
    - master
    - dev

addons:
  sonarcloud:
    organization: "sebastianwessel-github"
    token:
      secure: $SONAR_TOKEN

jobs:
  include:
    - stage: test
      name: "Integration tests"
      script: npm run test:integration
    - script: npm run lint && npm run test:unit
      name: "Unit tests"
    - stage: codecoverage
      name: "Sonarqube gateway"
      script:
#       - npm run combine-coverage
        - sonar-scanner
        - rm ./doc/coverages && npx codecov
    - stage: build
      name: "Build lib"
      script: npm run build
    - stage: npm release
      node_js: "10"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "mail@sebastianwessel.de"
        api_key: $NPM_API_KEY
        gem: eventstore-ts-client
        on:
          branch: master

stages:
  - test
  - codecoverage
  - name: build
    if: branch = master
  - name: npm release
    if: branch = master