dist: trusty

language: node_js

node_js:
  - "11"

git:
  depth: false

cache:
  directories:
    - "$HOME/.npm"
    - coverage
    - .nyc_output
    - dist

script: echo "Running tests against $(node -v) ..."

branches:
  only:
    - master
    - dev

addons:
  sonarcloud:
    organization: "sebastianwessel-github"
    token:
      secure: $SONAR_TOKEN

jobs:
  include:
    - stage: test
      name: "Integration tests"
      script: npm run test
    - stage: codecoverage
      name: "Sonarqube gateway"
      script:
        - git fetch --no-tags https://github.com/sebastianwessel/eventstore-ts-client.git +refs/heads/master:refs/remotes/origin/master
        - sonar-scanner
        - npx codecov
    - stage: build
      name: "Build lib"
      script: npm run build
    - stage: npm release
      node_js: "10"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "mail@sebastianwessel.de"
        api_key: $NPM_API_KEY
        gem: eventstore-ts-client
        on:
          branch: master

stages:
  - test
  - codecoverage
  - name: build
    if: branch = master
  - name: npm release
    if: branch = master