language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules
    - coverage

branches:
  only:
    - master
    - dev

script:
  - npm run test

after_success:
  - npm run build
  - npm install codecov -g
  - nyc report --reporter=json > coverage/coverage.json
  - codecov